### ISSUE TITLE
engram v2: incorrect punctuation in layout

### ISSUE THREAD

**Issue by sunaku** [cyanophage/cyanophage.github.io#1]
Hello, the Engram layout in your playground has incorrect punctuation mark locations: it should be [corrected to this](https://cyanophage.github.io/playground.html?layout=byou%27%22ldwvzciea%2C.htsnqgxjk-%3Frmfp).  Also, it would be more accurate to rename the layout label to "engram v2" since its official title is *Arno's Engram v2.0 ("Engram") layout*, [per its website](https://engram.dev/).  Thanks for your consideration.

**Comment by cyanophage** [comment]
The scoring model doesn't allow for changing of shifted characters. So having ' and " on two different keys doesn't do anything as one will be ignored.
