### ISSUE TITLE
Changes to effort weights do not reflect in effort score since 2024-ish

### ISSUE THREAD

**Issue by Intuos5** [cyanophage/cyanophage.github.io#3]
When I change the effort weights in the editor, the value for the total effort does not update.
I tested this in Microsoft Edge and Firefox.
![Cyanophage effort score](https://github.com/cyanophage/cyanophage.github.io/assets/63149655/c285398a-b9b4-4350-8969-e7e7423cbf48)

I think this issue started somewhere in either the last week or two of December or January 2024, because it worked fine before (perhaps its due to the introduction of mods/ word effort that since appeared).

**Comment by cyanophage** [comment]
Fixed!
