### ISSUE TITLE
Feature request: Add different languages (corpuses)

### ISSUE THREAD

**Issue by Intuos5** [cyanophage/cyanophage.github.io#4]
Right now, I am optimising a dual language layout and it would be really nice if I could add a couple of other languages to see all stats from. This is important, because a layout may be great in one language and terrible in another.
:)

**Comment by cyanophage** [comment]
Having a way to paste in your own text into the editor is on my list of things to do. I'm not sure how I would deal with characters like à, ü, é etc though.

**Comment by Intuos5** [comment]
Maybe it's something you could borrow from Oxey? There are quite a few language options and conversions to odd letters on his website.

**Comment by cyanophage** [comment]
The edit page has a "corpus" button in the top left now. You can paste in your own text and the stats on the page will update.
