### ISSUE TITLE
Feature Request: Easily copy effort grid

### ISSUE THREAD

**Issue by anantoghosh** [cyanophage/cyanophage.github.io#7]
Thanks for your work on this project, really helpful.

Currently when we want to compare layouts with a custom effort grid, what we need to do is open the layouts in each tab and then manually enter the effort grid for each of the layouts.

It would be nice if we could instead either easily copy and load the effort grid as a single string, it could be just another text input below the grid inputs or part of the url as you do with the layout keys or store the effort grid in local storage.

**Comment by cyanophage** [comment]
This is a good idea! Thanks. I've added a Copy and Paste button to the effort grid popup. Does that help?

**Comment by anantoghosh** [comment]
Absolutely! Everything is functioning perfectly. I truly appreciate your swift attention to this.
