### ISSUE TITLE
Own layouts not working properly.

### ISSUE THREAD

**Issue by rpnfan** [cyanophage/cyanophage.github.io#8]
When one tries to arrange layouts, there are glitches. For example move a few keys, change to a different key arrangement and to a few others, back and forth and the keys will not stay at the position one arranged them to or they will be shuffled up like that.

![image](https://github.com/cyanophage/cyanophage.github.io/assets/51239533/e2ca6393-6ab9-4f80-9be9-b68075f652ad)

When then saving the URL, with the layout and pasting that into a new browser window it will only show the Ergo layout and does not allow to switch to other key arrangements back.

**Comment by cyanophage** [comment]
This only happens when you try to put letters on the shift key on a row staggered layout. Just don't do that and it's fine

**Comment by rpnfan** [comment]
My layout is optimized for use on a standard staggered and a columnar staggered board. I have Shift on the lower right pinky key (/-key). Then your optimizer can not handle that, which is a pity. Limiting new layouts to not allow Shift or characters on any position does not allow to really optimize and try new approaches.

**Comment by cyanophage** [comment]
I was fixing something else and did this in the process. Working for you now?
